import { getArticles, getCategories } from "@/Http";
import { GetServerSideProps } from "next";
import { AxiosResponse } from "axios";
import { IArticle, ICategory, ICollectionResponse, IPagination } from "@/Types";
import Head from "next/head";
import React from "react";
import CategoriesTabs from "@/Components/CategoriesTabs";
import qs from "qs";
import Articles from "@/Components/Articles";
import { capitalFirstLetter, removeDash } from "@/utils";

interface IPropType {
  categories: {
    items: ICategory[];
    pagination: IPagination;
  };

  articles: {
    items: IArticle[];
    pagination: IPagination;
  };

  slug: string;
}

const category = ({ categories, articles, slug }: IPropType) => {
  const formattedTitle = () => {
    return capitalFirstLetter(removeDash(slug));
  };

  return (
    <div>
      <Head>
        <title>Coders Blog {formattedTitle()}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* //Articles Based on category */}
      <CategoriesTabs categories={categories.items} />

      <Articles articles={articles.items} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const options = {
    populate: ["author.avatar"],
    sort: ["id:desc"],
    filters: {
      category: {
        Slug: query.category,
      },
    },
  };

  const queryString = qs.stringify(options);

  //Categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await getCategories();

  //Articles
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await getArticles(queryString);

  // console.log(categories);
  return {
    props: {
      categories: {
        items: categories.data,
        pagination: categories.meta.pagination,
      },
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination,
      },

      slug: query.category,
    },
  };
};
export default category;
