import { getCategories } from "@/Http";
import { AxiosResponse } from "axios";
import { ICategory, ICollectionResponse } from "@/Types";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import CategoriesTabs from "@/Components/CategoriesTabs";

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
}

const Home: NextPage<IPropTypes> = ({ categories }) => {
  console.log(categories.items);
  return (
    <>
      <Head>
        <title>Coders Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CategoriesTabs categories={categories.items} />

      <div>hello world</div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  //categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await getCategories();

  console.log(categories);
  return {
    props: {
      categories: {
        items: categories.data,
      },
    },
  };
};

export default Home;
