import { getCategories } from "@/Http";
import { AxiosResponse } from "axios";
import { ICategory, ICollectionResponse } from "@/Types";
import { GetServerSideProps } from "next";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Coders Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>hello world</div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  //categories
  const { data }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await getCategories();

  return {
    props: {
      categories: {
        item: categories.data,
      },
    },
  };
};
